# =============================================================================
# Terraform Deployment Pipeline — ${project_name}
# Generated by spoke deployment — safe to customize
#
# This workflow deploys through dev → acceptance → prod in sequence.
# Each stage targets its GitHub environment. Configure protection rules
# (required reviewers, wait timers) in Settings > Environments to add
# approval gates between stages.
#
# You are free to:
#   - Add or remove stages to match your actual environments
#   - Change the runner label
#   - Add extra steps (integration tests, notifications, etc.)
#   - Adjust the trigger (schedule, push, pull_request, etc.)
#
# The only files that are auto-updated by the spoke deployment are
# config/spoke-outputs-<env>.tfvars and config/<env>.azurerm.tfbackend. All other files in this repo are yours.
# =============================================================================

name: Terraform Deploy - ${project_name}

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true

jobs:
  # ---------------------------------------------------------------------------
  # Stage 1: dev
  # ---------------------------------------------------------------------------
  deploy-dev:
    name: 'Deploy dev'
    runs-on: '${runner_label}'
    environment: dev

    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: $${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: $${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: $${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      with:
        terraform_version: ~1.9.0

    - name: Azure Login
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
      with:
        client-id: $${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: $${{ secrets.AZURE_TENANT_ID }}
        subscription-id: $${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure Git for private module access
      shell: bash
      env:
        GITHUB_TOKEN: $${{ secrets.GH_INTEGRATION_TOKEN }}
      run: |
        git config --global url."$${GITHUB_SERVER_URL/:\/\//://$GITHUB_TOKEN@}/".insteadOf "$GITHUB_SERVER_URL/"

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="config/dev.azurerm.tfbackend"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file="config/spoke-outputs-dev.tfvars" -no-color -input=false -out=tfplan

    - name: Terraform Plan Status
      run: |
        if [ "$${{ steps.plan.outcome }}" == "failure" ]; then
          echo "Terraform plan failed"
          exit 1
        fi

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      run: terraform apply tfplan

    - name: Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      id: output
      run: terraform output -json

  # ---------------------------------------------------------------------------
  # Stage 2: acceptance
  # Requires the dev stage to succeed. Add required reviewers in
  # Settings > Environments > acceptance to gate promotion.
  # ---------------------------------------------------------------------------
  deploy-acceptance:
    name: 'Deploy acceptance'
    runs-on: '${runner_label}'
    environment: acceptance
    needs: [deploy-dev]
    if: $${{ !failure() && !cancelled() }}

    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: $${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: $${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: $${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      with:
        terraform_version: ~1.9.0

    - name: Azure Login
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
      with:
        client-id: $${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: $${{ secrets.AZURE_TENANT_ID }}
        subscription-id: $${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure Git for private module access
      shell: bash
      env:
        GITHUB_TOKEN: $${{ secrets.GH_INTEGRATION_TOKEN }}
      run: |
        git config --global url."$${GITHUB_SERVER_URL/:\/\//://$GITHUB_TOKEN@}/".insteadOf "$GITHUB_SERVER_URL/"

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="config/acceptance.azurerm.tfbackend"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file="config/spoke-outputs-acceptance.tfvars" -no-color -input=false -out=tfplan

    - name: Terraform Plan Status
      run: |
        if [ "$${{ steps.plan.outcome }}" == "failure" ]; then
          echo "Terraform plan failed"
          exit 1
        fi

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      run: terraform apply tfplan

    - name: Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      id: output
      run: terraform output -json

  # ---------------------------------------------------------------------------
  # Stage 3: prod
  # Requires the acceptance stage to succeed. Add required reviewers in
  # Settings > Environments > prod to gate promotion.
  # ---------------------------------------------------------------------------
  deploy-prod:
    name: 'Deploy prod'
    runs-on: '${runner_label}'
    environment: prod
    needs: [deploy-acceptance]
    if: $${{ !failure() && !cancelled() }}

    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: $${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: $${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: $${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      with:
        terraform_version: ~1.9.0

    - name: Azure Login
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
      with:
        client-id: $${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: $${{ secrets.AZURE_TENANT_ID }}
        subscription-id: $${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure Git for private module access
      shell: bash
      env:
        GITHUB_TOKEN: $${{ secrets.GH_INTEGRATION_TOKEN }}
      run: |
        git config --global url."$${GITHUB_SERVER_URL/:\/\//://$GITHUB_TOKEN@}/".insteadOf "$GITHUB_SERVER_URL/"

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="config/prod.azurerm.tfbackend"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file="config/spoke-outputs-prod.tfvars" -no-color -input=false -out=tfplan

    - name: Terraform Plan Status
      run: |
        if [ "$${{ steps.plan.outcome }}" == "failure" ]; then
          echo "Terraform plan failed"
          exit 1
        fi

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      run: terraform apply tfplan

    - name: Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && steps.plan.outcome == 'success'
      id: output
      run: terraform output -json
